config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    omniauth_callbacks: "omniauth"
  }

  scope '/resources', module: :resources, as: 'resource' do
    resources :journals, only: [:update, :destroy]
    resources :questions, only: [:update, :destroy]
    resources :responses, only: [:update, :destroy]
    resources :entries, only: [:update, :destroy]
  end

  # Scenes
  scope module: :scenes, as: 'scenes' do
    get '/', to: 'current_journal#scene', as: 'current_journal'
    get 'auth', to: 'auth#scene', as: 'auth'
    get 'go', to: 'active_journal#scene', as: 'active_journal'
    get 'entry/:id', to: 'journal_entry#scene', as: 'journal_entry'
  end

  # action_add_question_to_current_journal_path
  # Actions
  scope module: :scenes, as: 'actions' do
    post 'sign_out', to: 'base#sign_out_action', as: 'sign_out'

    scope '/current_journal', controller: :current_journal do
      post :add_question, as: 'add_question'
      put :update_account, as: 'update_account'
      put :update_password, as: 'update_password'
      put :delete_account, as: 'delete_account'
      post 'delete_question/:id', action: 'delete_question', as: 'delete_question'
    end

    scope '/auth', controller: :auth do
      post :login, as: 'login'
      post :signup, as: 'signup'
    end

    scope '/go', controller: :active_journal do
      post :next, as: 'next_question'
      post :previous, as: 'previous_question'
    end

    scope '/entry/:id', controller: :journal_entry do
      post :delete_entry, as: 'delete_entry'
    end
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/scenes/current_journal/props/forms/_delete_account_form.html.erb
<%= form_for(current_user, url: action_path(:delete_account), html: { method: :put }, remote: true) do |f| %>

  <p class="prompt">Enter password to continue</p>

  <%= f.field_for(:current_password) do %>
    <% f.password_field :current_password, autocomplete: "off", placeholder: "Current password" %>
  <% end %>

  <%= f.submit "Delete Account" %>
<% end %>

app/views/scenes/current_journal/props/forms/_new_question_form.html.erb
<%= form_for(question,
              url: action_path(:add_question),
              class: "new-question-form",
              remote: 'true') do |f| %>

  <%= f.text_field :body, placeholder: "Enter new question..." %>
  <%= f.submit "Add" %>
<% end %>

app/views/scenes/current_journal/props/forms/_update_account_form.html.erb
<%= form_for(current_user, url: action_path(:update_account), html: { method: :put }, remote: true) do |f| %>

  <%= f.field_for(:email) do %>
    <% f.email_field :email, autofocus: true, autocomplete: "email", placeholder: "Email" %>
  <% end %>

  <%= f.submit "Update" %>
<% end %>

app/views/scenes/current_journal/props/forms/_update_password_form.html.erb
<%= form_for(current_user, url: action_path(:update_password), html: { method: :put }, remote: true) do |f| %>

  <%= f.field_for(:password) do %>
    <% f.password_field :password, autocomplete: "off", placeholder: "New password" %>
  <% end %>

  <%= f.field_for(:password_confirmation) do %>
    <% f.password_field :password_confirmation, autocomplete: "off", placeholder: "Confirm new password" %>
  <% end %>

  <%= f.field_for(:current_password) do %>
    <% f.password_field :current_password, autocomplete: "off", placeholder: "Current password" %>
  <% end %>

  <%= f.submit "Update" %>
<% end %>