config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    omniauth_callbacks: "omniauth"
  }

  scope '/resources', module: :resources, as: 'resource' do
    resources :journals, only: [:update, :destroy]
    resources :questions, only: [:update, :destroy]
    resources :responses, only: [:update, :destroy]
    resources :entries, only: [:update, :destroy]
  end

  # Scenes
  scope module: :scenes, as: 'scenes' do
    get '/', to: 'current_journal#scene', as: 'current_journal'
    get 'auth', to: 'auth#scene', as: 'auth'
    get 'go', to: 'active_journal#scene', as: 'active_journal'
    get 'entry/:id', to: 'journal_entry#scene', as: 'journal_entry'
  end

  # action_add_question_to_current_journal_path
  # Actions
  scope module: :scenes, as: 'actions' do
    post 'sign_out', to: 'base#sign_out_action', as: 'sign_out'

    scope '/current_journal', controller: :current_journal do
      post :add_question, as: 'add_question'
      put :update_account, as: 'update_account'
      put :update_password, as: 'update_password'
      put :delete_account, as: 'delete_account'
      post 'delete_question/:id', action: 'delete_question', as: 'delete_question'
    end

    scope '/auth', controller: :auth do
      post :login, as: 'login'
      post :signup, as: 'signup'
    end

    scope '/go', controller: :active_journal do
      post :next, as: 'next_question'
      post :previous, as: 'previous_question'
    end

    scope '/entry/:id', controller: :journal_entry do
      post :delete_entry, as: 'delete_entry'
    end
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/scenes/current_journal_controller.rb
class Scenes::CurrentJournalController < SceneController
  before_action :authenticate_user!

  def scene
    @questions = current_journal.ordered_questions
    @entries = current_journal.entries.order(created_at: :desc)
    @new_question = Question.new
  end

  def add_question
    if @question = current_journal.create_question(question_params)
      render_update(:question_added)
    else
      render json: @question.errors, status: :unprocessable_entity
    end
  end

  def update_account
    if current_user.update_without_password(user_params)
      render_update(:account_update_succeeded)
    else
      render_update(:account_update_failed)
    end
  end

  def delete_account
    if valid_current_password?
      current_user.destroy
      redirect_to('/')
    else
      render_update(:delete_account_failed)
    end
  end

  def update_password
    if valid_current_password? && current_user.update(password_params)
      render_update(:password_update_succeeded)
    else
      render_update(:password_update_failed)
    end
  end

  def delete_question
    @question = Question.find(params[:id])
    @question.destroy
  end

  private
  def question_params
    params.require(:question).permit(:body, :journal_id)
  end

  def user_params
    params.require(:user).permit(:email)
  end

  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end

  def current_password_param
    params[:user][:current_password]
  end

  def valid_current_password?
    current_user.valid_password?(current_password_param) || incorrect_current_password!
  end

  def incorrect_current_password!
    current_user.errors[:current_password] << "is incorrect"
    false
  end
end

app/views/scenes/current_journal/props/_new_question.html.erb
<%= form_with(model: question,
              url: action_path(:add_question),
              class: "new-question-form") do |form| %>
  <% if question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.text_field :body, placeholder: "Enter new question..." %>
  <%= form.submit "Add" %>
<% end %>

app/views/scenes/current_journal/props/_questions_card.html.erb
<div class="card-canvas questions-card-canvas" data-card-canvas="questions">
  <div class="card questions-card">
    <div class="card-content">
      <p class="card-title">
        <%= dynamic_text_for(current_journal, :title, placeholder: "Untitled") %>
      </p>
      <p class="card-subtitle">
        Questions
      </p>

      <ol class="edit-questions">
        <% @questions.each do |question| %>
          <%= render_prop :edit_question_item, question: question %>
        <% end %>
      </ol>
    </div>
    <div class="card-actions">
      <div class="add-question">
        <%= render_prop :new_question, question: @new_question %>
      </div>
    </div>
  </div>

  <p class="close">
    Close
  </p>
</div>

app/views/scenes/current_journal/props/_settings_card.html.erb
<div class="card-canvas settings-card-canvas" data-card-canvas="settings">
  <div class="card form-card settings-card">
    <div class="card-content">
      <p class="card-title">
        Account Settings
      </p>
      <%= render_prop(:update_account) %>
    </div>

    <div class="card-actions">
      <ul class="card-links">
        <li>
          <%= link_to "Signout", "/users/sign_out", method: :delete, class: "show-signup-tab" %>
        </li>
        <li>
          <%= link_to "Delete Account", "#", class: "show-delete-tab" %>
        </li>
      </ul>
    </div>
  </div>

  <p class="close">
    Close
  </p>
</div>

app/views/scenes/current_journal/props/_update_account.html.erb
<%= form_for(current_user, url: registration_path(:user), html: { method: :put }) do |f| %>
  <div class="field">
    <%= f.email_field :email, autofocus: true, autocomplete: "email", placeholder: "Email" %>
  </div>

  <div class="field">
    <%= f.password_field :password, autocomplete: "off", placeholder: "Enter new password" %>
  </div>

  <div class="field">
    <%= f.password_field :password_confirmation, autocomplete: "off", placeholder: "Confirm new password" %>
  </div>

  <div class="field">
    <%= f.password_field :current_password, autocomplete: "off", placeholder: "Enter current password" %>
  </div>

  <%= f.submit "Update" %>
<% end %>