config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    omniauth_callbacks: "omniauth"
  }

  scope '/resources', module: :resources, as: 'resource' do
    resources :journals, only: [:update, :destroy]
    resources :questions, only: [:update, :destroy]
    resources :responses, only: [:update, :destroy]
    resources :entries, only: [:update, :destroy]
  end

  # Scenes
  scope module: :scenes, as: 'scenes' do
    get '/', to: 'current_journal#scene', as: 'current_journal'
    get 'auth', to: 'auth#scene', as: 'auth'
    get 'go', to: 'active_journal#scene', as: 'active_journal'
    get 'entry/:id', to: 'journal_entry#scene', as: 'journal_entry'
  end

  # action_add_question_to_current_journal_path
  # Actions
  scope module: :scenes, as: 'actions' do
    post 'sign_out', to: 'base#sign_out_action', as: 'sign_out'

    scope '/current_journal', controller: :current_journal do
      post :add_question, as: 'add_question'
      put :update_account, as: 'update_account'
      put :update_password, as: 'update_password'
      put :delete_account, as: 'delete_account'
      post 'delete_question/:id', action: 'delete_question', as: 'delete_question'
    end

    scope '/auth', controller: :auth do
      post :login, as: 'login'
      post :signup, as: 'signup'
    end

    scope '/go', controller: :active_journal do
      post :next, as: 'next_question'
      post :previous, as: 'previous_question'
    end

    scope '/entry/:id', controller: :journal_entry do
      post :delete_entry, as: 'delete_entry'
    end
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/scene_controller.rb
class SceneController < ApplicationController
  layout 'scene'

  def render_update(update, **locals)
    render("#{params[:controller]}/updates/#{update}", locals: locals)
  end

  def scene_path(scene, *args)
    send("scenes_#{scene}_path", *args)
  end

  def current_journal
    if current_user
      @current_journal ||= current_user.get_or_create_journal
    end
  end

  helper_method :current_journal

  def sign_out_action
    sign_out_and_redirect(:user)
  end
end

app/controllers/scenes/active_journal_controller.rb
class Scenes::ActiveJournalController < SceneController
  before_action :authenticate_user!
  before_action :set_entry, only: [ :previous, :next ]

  def scene
    if journal_in_progress?
      set_entry and set_response
    else
      new_entry and redirect_to_first_question
    end
  end

  def next
    if on_last_question?
      redirect_to scene_path(:journal_entry, @entry)
    else
      redirect_to_question(+1)
    end
  end

  def previous
    if on_first_question?
      exit_entry
    else
      redirect_to_question(-1)
    end
  end

  def exit_entry
    should_delete_entry = true

    @entry.responses.each do |response|
      should_delete_entry = false if !response.body.nil?
    end

    delete_entry if should_delete_entry
    redirect_to scene_path(:current_journal)
  end

  private

  def delete_entry
    @entry.destroy
  end

  def new_entry
    @entry = current_journal.create_entry_with_questions
  end

  def set_entry
    @entry = current_journal.entries.find(params[:entry])
  end

  def set_response
    @response = @entry.ordered_responses[params[:question].to_i - 1]
  end

  def journal_in_progress?
    params[:entry]
  end

  def redirect_to_first_question
    redirect_to scene_path(:active_journal, entry: @entry.id, question: 1)
  end

  def on_first_question?
    params[:question].to_i == 1
  end

  def on_last_question?
    params[:question].to_i >= @entry.responses.length
  end

  def last_question
    @entry.responses.order(position: :asc).last
  end

  def redirect_to_question(val)
    redirect_to scene_path(:active_journal, {
      entry: @entry.id,
      question: params[:question].to_i + val
    })
  end
end

app/controllers/scenes/auth_controller.rb
class Scenes::AuthController < SceneController
  before_action :redirect_if_user_signed_in

  def scene
    @user = User.new
  end

  def signup
    @user = User.new(user_params)
    if @user.save
      sign_in_and_redirect(@user)
    else
      render_update(:signup_failed)
    end
  end

  def login
    @user = User.find_for_authentication(email: user_params[:email])

    if @user && !@user.new_record? && @user.valid_password?(user_params[:password])
      sign_in_and_redirect(@user)
    else
      @user = User.new(user_params)
      render_update(:login_failed)
    end
  end

  private

  def redirect_if_user_signed_in
    redirect_to('/') if user_signed_in?
  end

  def user_params
    params.require(:user).permit(:password, :email, :password_confirmation)
  end
end

app/controllers/scenes/base_controller.rb
class Scenes::BaseController < ApplicationController
  layout 'scene'

  helper_method :current_journal

  def render_update(update, **locals)
    render("#{params[:controller]}/updates/#{update}", locals: locals)
  end

  def scene_path(scene, *args)
    send("scenes_#{scene}_path", *args)
  end

  def current_journal
    if current_user
      @current_journal ||= current_user.get_or_create_journal
    end
  end

  def sign_out_action
    sign_out_and_redirect(:user)
  end
end

app/controllers/scenes/current_journal_controller.rb
class Scenes::CurrentJournalController < SceneController
  before_action :authenticate_user!

  def scene
    @questions = current_journal.ordered_questions
    @entries = current_journal.entries.order(created_at: :desc)
    @new_question = Question.new
  end

  def add_question
    if @question = current_journal.create_question(question_params)
      render_update(:question_added)
    else
      render json: @question.errors, status: :unprocessable_entity
    end
  end

  def update_account
    if current_user.update_without_password(user_params)
      render_update(:account_update_succeeded)
    else
      render_update(:account_update_failed)
    end
  end

  def delete_account
    if valid_current_password?
      current_user.destroy
      redirect_to('/')
    else
      render_update(:delete_account_failed)
    end
  end

  def update_password
    if valid_current_password? && current_user.update(password_params)
      render_update(:password_update_succeeded)
    else
      render_update(:password_update_failed)
    end
  end

  def delete_question
    @question = Question.find(params[:id])
    @question.destroy
  end

  private
  def question_params
    params.require(:question).permit(:body, :journal_id)
  end

  def user_params
    params.require(:user).permit(:email)
  end

  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end

  def current_password_param
    params[:user][:current_password]
  end

  def valid_current_password?
    current_user.valid_password?(current_password_param) || incorrect_current_password!
  end

  def incorrect_current_password!
    current_user.errors[:current_password] << "is incorrect"
    false
  end
end

app/controllers/scenes/journal_entry_controller.rb
class Scenes::JournalEntryController < SceneController
  before_action :authenticate_user!

  def scene
    @entry = current_journal.entries.find(params[:id])
    @responses = @entry.ordered_responses
  end

  def delete_entry
    @entry = current_journal.entries.find(params[:id])
    @entry.destroy
    redirect_to '/'
  end
end

app/views/scenes/app/_new_question.html.erb
<%= form_with(model: question, url: resource_questions_path(question), class: "new-question-form") do |form| %>
  <% if question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :journal_id, value: journal_id %>

  <%= form.text_field :body, placeholder: "Enter new question..." %>
  <%= form.submit "Add" %>
<% end %>

app/views/scenes/app/journal.html.erb
<div class="flex-container">
  <div class="journal">

    <h1 class="h1-like journal-title">
      <%= editable_text(@journal, :title) %>
    </h1>
    <p class="journal-caption">
      <%= editable_text(@journal, :caption, placeholder: "Enter a caption for your journal...") %>
    </p>

    <div class="actions">
      <%= link_to "#", class: "icon-button dull", data: { action: "showCard", "card-tag": "history" } do %>
        <div class="icon-button--image">
          <img src="<%= asset_path('history') %>" />
        </div>
        <div class="icon-button--text">
          History
        </div>
      <% end %>

      <%= link_to "#", class: "icon-button large" do %>
        <div class="icon-button--image">
          <img src="<%= asset_path('pencil') %>" />
        </div>
        <div class="icon-button--text">
          Start
        </div>
      <% end %>

      <%= link_to "#", class: "icon-button dull", data: { action: "showCard", "card-tag": "questions" } do %>
        <div class="icon-button--image">
          <img src="<%= asset_path('question') %>" />
        </div>
        <div class="icon-button--text">
          Questions
        </div>
      <% end %>
    </div>

    <%= render partial: 'questions_card.html.erb' %>
    <%= render partial: 'history_card.html.erb' %>
  </div>
</div>

app/views/scenes/app/my_journals.html.erb
<p id="notice"><%= notice %></p>

<h1> Your Journals </h1>

<% @journals.each do |journal| %>
  <%= link_to scenes_journal_path(journal) do %>
    <%= journal.title %> -
    <%= journal.caption %>
  <% end %>
<% end %>

<%= render partial: '/scenes/partials/new_journal',
    locals: { journal: @new_journal } %>